name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main   # Trigger on push to main
  workflow_dispatch:   # Allow manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed to push to gh-pages

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # Step 3: Install dependencies inside frontend/app
      - name: Install dependencies
        run: npm install
        working-directory: frontend/app

      # Step 4: Build React app with environment variables
      - name: Build React app
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        run: npm run build
        working-directory: frontend/app

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/app/build
